-- $Id: bnf.bnf,v 1.2 2012/09/08 15:58:11 luis Exp $
-- vim: sw=4 ts=4 ai nu
-- Author: Luis Colorado <lc@luiscoloradosistemas.com>
-- Date: mar ago 21 08:48:42 CEST 2012
-- Disclaimer: (C) 2012 LUIS COLORADO SISTEMAS S.L.U.
--                 All rights reserved.

grammar ::= grammar rule | rule. -- list of rules.

rule ::= IDENT '::=' alternative_list ';'. -- fixed syntax

alternative_list ::= alternative_list '|' term_list
    | term_list. -- list of alternatives with at least one term_list.

term_list ::= term_list term
    |. -- empty


term ::= -- a term can be different things.
      IDENT
    | STRING
    | '{' alternative_list '}'
    | '[' alternative_list ']'
    | '(' alternative_list ')'.

-- $Id: bnf.bnf,v 1.2 2012/09/08 15:58:11 luis Exp $
