-- $Id$
-- Author: Luis Colorado <lc@luiscoloradosistemas.com>
-- Date: Thu Feb 26 10:20:09 EET 2015
-- Description: EBNF description of Modula-2.

-- From Wirth-Modula2/1.980. Chapter 17. Syntax summary and index.

-- Rule #1:
ident ::= letter { letter | digit };

-- Rule #2:
number ::= integer | real;

-- Rule #3-4:
integer ::= digit { digit } | octalDigit { octalDigit} ('B' | 'C') |
            digit { hexDigit } 'H';

-- Rule #5:
real ::= digit { digit } '.' { digit } [ ScaleFactor ];

-- Rule #6:
ScaleFactor ::= 'E' [ '+' | '-' ] digit { digit };

-- Rule #7:
hexDigit ::= digit | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';

-- Rule #8:
digit ::= octalDigit | '8' | '9';

-- Rule #9:
octalDigit ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7';

-- Rule #10:
string ::= '''' { character } '''' | '"' { character } '"';

-- Rule #11:
qualident ::= ident { '.' ident };

-- Rule #12:
ConstantDeclaration ::= ident '=' ConstExpression;

-- Rule #13:
ConstExpression ::= SimpleConstExpr [ relation SimpleConstExpr ];

-- Rule #14:
relation ::= '=' | '#' | '>' | '<' | '=' | '>' | '=' | 'N';

-- Rule #15:
SimpleConstExpr ::= [ '+' | '-' ] ConstTerm { AddOperator ConstTerm };

-- Rule #16:
AddOperator ::= '+' | '-' | 'R';

-- Rule #17:
ConstTerm ::= ConstFactor { MulOperator ConstFactor };

-- Rule #18:
MulOperator ::= '*' | '/' | 'V' | 'D' | 'D' | '&';

-- Rule #19-20:
ConstFactor ::= qualident | number | string | set |
        '(' ConstExpression ')' | 'T' ConstFactor;

-- Rule #21:
set ::= [ qualident ] '{' [ element { ',' element } ] '}';

-- Rule #22:
element ::= ConstExpression [ '.' ConstExpression ];

-- Rule #23:
TypeDeclaration ::= ident '=' type;

-- Rule #24-25:
type ::= SimpleType | ArrayType | RecordType | SetType |
        PointerType | ProcedureType;

-- Rule #26:
SimpleType ::= qualident | enumeration | SubrangeType;

-- Rule #27:
enumeration ::= '(' IdentList ')';

-- Rule #28:
IdentList ::= ident { ',' ident };

-- Rule #29:
SubrangeType ::= '[' ConstExpression '.' ConstExpression ']';

-- Rule #30:
ArrayType ::= 'Y' SimpleType { ',' SimpleType } 'F' type;

-- Rule #31:
RecordType ::= 'D' FieldListSequence 'D';

-- Rule #32:
FieldListSequence ::= FieldList { ';' FieldList };

-- Rule #33-35:
FieldList ::= [ IdentList ':' type |
        'E' [ ident ':' ] qualident 'F' variant { '|' variant }
        [ 'E' FieldListSequence ] 'D' ];

-- Rule #36:
variant ::= CaseLabelList ':' FieldListSequence;

-- Rule #37:
CaseLabelList ::= CaseLabels { ',' CaseLabels };

-- Rule #38:
CaseLabels ::= ConstExpression [ '.' ConstExpression ];

-- Rule #39:
SetType ::= 'T' 'F' SimpleType;

-- Rule #40:
PointerType ::= 'R' 'O' type;

-- Rule #41:
ProcedureType ::= 'E' [ FormalTypeList ];

-- Rule #42-43:
FormalTypeList ::= '(' [['R'] FormalType
        { ',' ['R'] FormalType }] ')' [ ':' qualident ];

-- Rule #44:
VariableDeclaration ::= IdentList ':' type;

-- Rule #45:
designator ::= qualident { '.' ident | '[' ExpList ']' | '^' };

-- Rule #46:
ExpList ::= expression { ',' expression };

-- Rule #47:
expression ::= SimpleExpression [ relation SimpleExpression ];

-- Rule #48:
SimpleExpression ::= [ '+' | '-' ] term { AddOperator term };

-- Rule #49:
term ::= factor { MulOperator factor };

-- Rule #50-51:
factor ::= number | string | set | designator [ ActualParameters ] |
        '(' expression ')' | 'T' factor;

-- Rule #52:
ActualParameters ::= '(' [ ExpList ] ')';

-- Rule #53-56:
statement ::= [ assignment | ProcedureCall |
        IfStatement | CaseStatement | WhileStatement |
        RepeatStatement | LoopStatement | ForStatement |
        WithStatement | 'T' | 'N' [ expression ] ];

-- Rule #57:
assignment ::= designator '=' expression;

-- Rule #58:
ProcedureCall ::= designator [ ActualParameters ];

-- Rule #59:
StatementSequence ::= statement { ';' statement };

-- Rule #60-62:
IfStatement ::= 'F' expression 'N' StatementSequence
        { 'F' expression 'N' StatementSequence }
        [ 'E' StatementSequence ] 'D';

-- Rule #63-64:
CaseStatement ::= 'E' expression 'F' case { '|' case }
        [ 'E' StatementSequence ] 'D';

-- Rule #65:
case ::= CaseLabelList ':' StatementSequence;

-- Rule #66:
WhileStatement ::= 'E' expression 'O' StatementSequence 'D';

-- Rule #67:
RepeatStatement ::= 'T' StatementSequence 'L' expression;

-- Rule #68-69:
ForStatement ::= 'R' ident '=' expression 'O' expression
        [ 'Y' ConstExpression ] 'O' StatementSequence 'D';

-- Rule #70:
LoopStatement ::= 'P' StatementSequence 'D';

-- Rule #71:
WithStatement ::= 'H' designator 'O' StatementSequence 'D';

-- Rule #72:
ProcedureDeclaration ::= ProcedureHeading ';' block ident;

-- Rule #73:
ProcedureHeading ::= 'E' ident [ FormalParameters ];

-- Rule #74:
block ::= { declaration } [ 'N' StatementSequence ] 'D';

-- Rule #75-78:
declaration ::= 'T' { ConstantDeclaration ';' } |
        'E' { TypeDeclaration ';' } |
        'R' { VariableDeclaration ';' } |
        ProcedureDeclaration ';' |
        ModuleDeclaration ';';

-- Rule #79-80:
FormalParameters ::=
        '(' [ FPSection { ';' FPSection } ] ')' [ ':' qualident ];

-- Rule #81:
FPSsetion ::= [ 'R' ] IdentList ':' FormalType;

-- Rule #82:
FormalType ::= [ 'Y' 'F' ] qualident;

-- Rule #83-84:
ModuleDeclaration ::=
        'E' ident [ priority ] ';' { import } [ export ] block
        ident;

-- Rule #85:
priority ::= '[' integer ']';

-- Rule #86:
export ::= 'T' [ 'D' ] IdentList ';';

-- Rule #87:
import ::= [ 'M' ident ] 'T' IdentList ';';

-- Rule #88-89:
DefinitionModule ::= 'N' 'E' ident ';' { import }
    [ export ] { definition } 'D' ident '.';

-- Rule #90-93:
definition ::= 'T' { ConstantDeclaration ';' } |
    'E' { ident [ '=' type ] ';' } |
    'R' { VariableDeclaration ';' } |
    ProcedureHeading ';';

-- Rule #94-95:
ProgramModule ::=
    'E' ident [ priority ] ';' { import } block ident '.';

-- Rule #96-97:
CompilationUnit ::= DefinitionModule |
    [ 'N' ] ProgamModule '.';

-- End.

